### ISSUE TITLE
Comparison to oz

### ISSUE THREAD

**Issue by jorinvo** [jsa-aerial/hanami#1]
Hi there, hanami looks great!
My first thought would be how this relates to [oz](https://github.com/metasoarous/oz). 
Just as suggestion, maybe you could mention in the readme in which way they differ?
Thank you :)

**Comment by jsa-aerial** [comment]
They are totally different. Hanami is a library/framework for creating visualization applications in Clojure(Script) using Vega-Lite and Vega.  Both the frontend (Cljs) and backend (Clj) are intended as bases for creating applications. The parameterized template system works in both client and server and is unique - all other 'bindings' (Altair for Python being the most complete) are typical procedural and/or OO classes/attributes - including Oz, which actually has almost nothing.

Oz is a simple app which can send VGL and VG specs to a browser client for display. It has basically no support for creating specs and nothing for page layouts. It uses an old deprecated version of react (reagent). And it uses a very clumsy and heavy weight msg system (Sente with loads of baggage).

Saite, is, in spirit, somewhat similar to Oz. But it is vastly more capable. It is a mini client/server app built with Hanami using several of Hanami's framework aspects - the tabbing system, the custom tab capability, the page header custom function, the multi named session capability (for sharing), and the powerful recursively transformed template system for generating VGL/VG specs.

**Comment by jorinvo** [comment]
Sounds awesome! Was thinking about looking int Oz for a small project soon. Then I will put that energy towards Saite instead :) Thanks for explaining!

**Comment by jorinvo** [comment]
Sounds great! Thanks!
