### ISSUE TITLE
version update at Clojars?

### ISSUE THREAD

**Issue by kmob** [jsa-aerial/hanami#11]
Hanami looks like a great project. I tried the ClientOnly example today and find the project is built for aerial.hanami "0.7.0" but aerial.hanami "0.6.0" is the latest available at Clojars. 

Do you know when 7 will be released to Clojars?

Thanks for all the hard work!

**Comment by jsa-aerial** [comment]
Thanks for the interest!

0.7.0 was an interim version - not released

But just released 0.8.0, so should be good to go!

**Comment by jumarko** [comment]
README.md shows version 0.10.0 but I could only find 0.8.0 on clojars: https://clojars.org/aerial.hanami

**Comment by jsa-aerial** [comment]
It's even worse than that - current real version is 0.10.11 - but as you noticed I haven't pushed any of these to Clojars.  There's no good reason for that per se - other than a lot of (fairly subtle) changes needed to support Saite.  Let me push the 0.10.11 version and ping here when done

**Comment by jsa-aerial** [comment]
OK, version 0.10.11 is now on clojars
