### ISSUE TITLE
Broken index.html link

### ISSUE THREAD

**Issue by Ramblurr** [jsa-aerial/hanami#14]
The readme docs [state](https://github.com/jsa-aerial/hanami#resource-requirements)

> The basic resource requirements are the various stylesheets, mostly in support of re-com, that are shown in the development 'landing page' [index.html](https://github.com/jsa-aerial/hanami/blob/master/resources/public/index.html). When you create your own index.html landing page - or generate it dynamically - you will need to include these resources.

But the link is broken: https://github.com/jsa-aerial/hanami/blob/master/resources/public/index.html

**Comment by jsa-aerial** [comment]
Good catch.  That needed to be moved under `public/Fig` for resource sanity:

https://github.com/jsa-aerial/hanami/blob/master/resources/public/Fig/index.html
