### ISSUE TITLE
Question: Extract out xform functionality

### ISSUE THREAD

**Issue by jamesnyika** [jsa-aerial/hanami#15]
Just wanted to know if the team has considered extracting out the xform and templating capabilities and made them generic and not specific to visualization ? or.. does it exist elsewhere in another form or by aanother name ? thanks

**Comment by jsa-aerial** [comment]
Yes, both of those have been discussed and thought through in the past.  It is not entirely clear that pulling it out as a standalone lib outside the context of some domain (for example, VG/VGL visualization specs) makes a lot of sense.  Pulling out the VG/VGL domain version probably does make sense and I've discussed this with Daniel a bit in the past.

**Comment by jamesnyika** [comment]
Yes.. I actually am thinking of a mechanism for applying rules (actually accounting rules) to a set of accounting transactions. What I like about xform is the way you can define ahead of time in a very compact way, the rules for substitution and the ability to have great defaults without figuring out a lot of exceptions. So a generic variable templating engine - it would be fantastic. 

 Just a thought.. I can probably use it as it is.. but I would have to ignore a lot of stuff. Alternatively, if you know of something else out there that works close to the same or just as nice (that is NOT a rules engine).. kindly give me a pointer to it. Right now, Specter is the only thing that comes to mind but it requires a lot more work that this looks like it will need

**Comment by jsa-aerial** [comment]
Interesting.  I would have thought a rules engine is *exactly* what you are looking for! :)  If you are not looking for that, then there isn't really anything I know of that would not require various additional assembly.  Like xform itself, which is built on top of Specter.  Could you say a bit about why a rule engine (like core.logic) doesn't fit your use case?

Using it as is as a *test* to see if you can actually do what you want with it, might be an interesting first step.  You would indeed need to ignore everything except the base *machinery* in `aerial.hanami.common`.  You would need to redefine the values in `_defaults` and, if needed, `subkeyfns`.  After that, you should be good to go on trying it out for your domain.  If it works well for you, that would indeed raise the priority of pulling it out as a standalone.

One thing to note is that the default substitution keys

```clojure
 ::rmv-empty? true
 ::use-defaults? true
```

are domain independent transformation *control* keys.  If the first is false, empty collections will not be removed.  If the second is false, the value of `_defaults` will not be used - only the what you pass into xform.

**Comment by jamesnyika** [comment]
Thank you for that. Indeed a core.logic based approach may be appropriate. I have not explored it yet. The values that substitution are expected to change often based a scoring mechanism. For example, if I keep noticing that revenue is always assigned to certain accounts, I want to dynamically define new substitutions that reflect that changing reality. but your pointers are excellent.. I will try it out and if it does work out I will keep you guys posted. Thank you very much
