### ISSUE TITLE
Why depend on reagent 0.7.0 not 0.8.1 ?

### ISSUE THREAD

**Issue by hipitihop** [jsa-aerial/hanami#7]
The project.clj uses dependency [reagent "0.7.0"] and has #_[reagent "0.8.1"] commented out. Is there a reason for this, is there an issue with later reagent ?

**Comment by jsa-aerial** [comment]
Update: other than seeming a bit more sluggish in a couple cases, 0.8.1 seems to work fine. Thinking back, I believe the issue as a skew with the available CLJSJS React. Needed a newer version and for some reason that took longer than expected. Or something like that.

Anyway, I think I will move to 0.8.1 for next release. Unless I find something more problematic before the release.
