### ISSUE TITLE
Simple example just using clojurescript client side and reagent

### ISSUE THREAD

**Issue by chagasVinicius** [jsa-aerial/hanami#9]
Hi, 

I want to use the hanami library to create a dashboard, but I am having problems to understand how I can use only the clojurescript side without the need to create the hanami server side.

Could someone clarify how I can proceed? Why even reading the documents and studying the saite example, I can not figure out how to create a graph without the hanami ecosystem (server and client).

Best regards,
Vinicius

**Comment by jsa-aerial** [comment]
The major thing you need to do is figure out what your landing page is and make sure to start your client side running when it has finished loading. When starting your client, do not use the hc/start function as it assumes a server. You will need to write your own client start function that inits things as you need.

If you want to use the tab system, you will need to at least perform the initialization for it found in hc/register:

```Clojure
(update-adb
              [:tabs] (let [cur-ratom (rgt/atom nil)
                            tabs-ratom (rgt/atom [])]
                        {:current cur-ratom
                         :active tabs-ratom
                         :bars [horizontal-bar-tabs
                                :model cur-ratom
                                :tabs tabs-ratom
                                :on-change #(reset! cur-ratom %)]}))
```
If you use the tab system, you will want to call the `tabs` component as part of your main reagent component render. Have a look at hc/hanami-main for ideas.

If you don't use the tab system, you don't need to init it and you will be creating your pages/subsections/whatever entirely on your own, probably with a mix of hiccup and re-com. In this case you will want to call the `vgl` component for rendering vega and vega-lite explicitly where it makes sense for your application. Have a look at `aerial.saite.core/vis-panel` for an example.

**Comment by jsa-aerial** [comment]
I think this issue shows a need to refactor some aspects of cljs hc/core. I've not actually made a entirely client side application and so, I see now it would be nice to split things like `hc/register` up a bit so you could just call a `tabs-init` without fooling around with the actual code. I'm sure there are some other such cases as well.

**Comment by teodorlu** [comment]
Chiming in that a simple client-only example would be super helpful. I just feel that ClojureScript + Vega + Re-frame (or something else) is _right_ for data visualization.

Thanks for building and releasing this! I've just skimmed the README, so I don't have full context. But coming from Altair, and reading about your approach, I'm excited!

**Comment by jsa-aerial** [comment]
I am working on the client only aspects and have made changes to make this simpler. I am also looking to have some _very_ simple example for ithis.

**Comment by jsa-aerial** [comment]
@chagasVinicius , @teodorlu , @johnmn3, @smee

I'm ready to release 0.7.0 (I think but testing looks good), which contains many changes for making client only applications both simpler and easier. There is a huge amount of new documentation - and an entire section on creating client only apps. Furthermore, there is a very simple client only application now in the `examples` directory. This is discussed in the _Client Only Apps_ section of the documentation.

If one or more of you would look this over and see if it more or less works for you, that would be great. If you think it still isn't clear, that would not be as great :), but would be helpful if you could say how/why it isn't.

**Comment by teodorlu** [comment]
Sounds great! I'll have a look.

**Comment by teodorlu** [comment]
I don't feel like I've given Hanami enough effort to pass judgement, but here's some thoughts anyway:

- Surprisingly little boilerplate code was required
- Note that I had to run a `lein install` in the root project to get the example working
- I feel like there's a lot going on under the hood. For example, the main reagent component is linked in from the library code (`aerial.hanami.core/hanami-main`)

**Comment by jsa-aerial** [comment]
> Surprisingly little boilerplate code was required

That is a goal for this stuff. That way you can focus on your application code, not so much library hoop jumping.

> Note that I had to run a lein install in the root project to get the example working

Right - as noted, I was holding off releasing until I got a bit of feedback on this to see if something else should be adjusted/added. Sounds like it is OK to just release it and announce it.

> I feel like there's a lot going on under the hood.

In this case (the example client app) that is true as it uses both the library aspects (templates in particular) and most framework aspects (this is why hanami-main is referred as noted [here](https://github.com/jsa-aerial/hanami#application-initialization) in the documentation for "Client Only Apps")

**Comment by johnmn3** [comment]
IMO, this library solves two separate problems:
 1) Parameterizing vg/vl specs
 2) A state management system for controlling interaction with the charts

A lot of consumers like myself, building things for many different platforms, are looking for a solution to 1. Many folks in the data science world are looking for an easy solution to number 2.

Unfortunately, folks in my boat will have a hard time leveraging this library because I cannot simply drop the lib in on any platform and use only it's spec parameterization features. The tab management system and all the other interface state management logic are coupled with the graph state/spec management bits. And it's all global. I'd like to pipeline graph state management, scoped to each graph individually. This can usually be accomplished with a "ctx" or "env" atom that you thread through each function, so that the given function does not need to call out to a global atom. In some systems I've built, I allow for both global and local scoped function by grabbing the global atom if the local one passed in is nil.

I've had to resort to building my own spec parameterization solution for now, but your transformation system is pretty awesome and if you want help splitting it out, let me know!

**Comment by jsa-aerial** [comment]
>  The tab management system and all the other interface state management logic are coupled with the graph state/spec management bits

That is not true. As noted in several places, (in particular [here](https://github.com/jsa-aerial/hanami#library-overview) the template  and transformation system have nothing to do with the tab system or any of the other 'framework' bits

> And it's all global. 

It's not clear what this means. It is worth noting that all the state is held in the `app-db`, which is scoped by 'action class' via paths

> I'd like to pipeline graph state management, scoped to each graph individually

This isn't clear either, but each specification (and associated visualization) is intended to be addressed individually by it's `:vid`

> I've had to resort to building my own spec parameterization solution for now, but your transformation system is pretty awesome and if you want help splitting it out, let me know!

The template and transform system is completely independent of any of the framework bits. This should be clear by the fact that the server side does not know anything at all about tabs, headers, hiccup, re-com, reagent, react components, etc. And yet it uses the template and xform system in all the examples.

Now, if you are trying to say it would be nice to have the template and xform system as an independent library, that sounds reasonable and would actually be trivial to do.  Basically just create a new repo, put cljc common.cljc and templates.cljc and build a new jar from it.  The only thing to figure out is file data sources as they do not have cljs support just yet. But that was and is intended

**Comment by johnmn3** [comment]
> That is not true. As noted in several places, (in particular here the template and transformation system have nothing to do with the tab system or any of the other 'framework' bits

Ah, perhaps I just didn't read the code base carefully enough then. In any case, many folks (probably like myself) will be working with systems that already have strong opinions about state management. I'm not trying to publicly critique your design decisions though, so if you want any help or feedback for those kinds of use cases, in the interest of generalizing the transformation piece, feel free to dm me on clojurian slack @john
